---
- name: Install Apache, MySQL, and PHP
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - mysql-community-server
    - php
    - php-mysql

- name: Start and enable Apache
  systemd:
    name: httpd
    enabled: yes
    state: started  

- name: Install MariaDB on CentOS database host
  dnf:
    name: "{{ lamp_db_packages_centos }}"
    state: present
    update_cache: yes
  when:
    - lamp_component == 'db'
    - ansible_distribution == "CentOS"

- name: Enable and start MariaDB on CentOS database host
  systemd:
    name: mariadb
    enabled: yes
    state: started
  when:
    - lamp_component == 'db'
    - ansible_distribution == "CentOS"