---
- name: Install Nagios on CentOS
  yum:
    name: nagios
    state: present
  when: ansible_distribution == "CentOS"

- name: Start Nagios Service on CentOS
  service:
    name: nagios
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"