[ubuntu_servers]
server1 ansible_host=192.168.56.111 ansible_user=jalene

[centos_servers]
server4 ansible_host=192.168.56.115 ansible_user=jalene ansible_python_interpreter=/usr/libexec/platform-python

[web_servers:children]
ubuntu_servers
centos_servers